---
deployement:
  tasks:
    - export DEPLOYPATH=/home/cp964669p05/public_html/
    - export DISTPATH=/app/out/
    - npm install
    - npm run build
    - npm run export
    - /bin/cp -R $DISTDPATH $DEPLOYPATH